install.packages('ggplot2')
install.packages('ggmap')
install.packages('raster')
install.packages('rasterVis')
install.packages('httr')
install.packages('zoo')
install.packages('maptools')
install.packages("rjson")
install.packages("dbscan")
install.packages("fpc")

require(devtools)
install_version("rmarkdown", version = "2.13", repos = "https://cran.r-project.org")
